bargain/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from .views import home

urlpatterns = [
    # Examples:
    # url(r'^$', 'bargain.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    url(r'^', include('authentication.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^merchant/', include('merchant.urls')),
]

merchant/urls.py
from django.conf.urls import url
from merchant.views import ManageProductView, offering_list_view, edit_merchant_product, offering_action


urlpatterns = [
    url(r'^(?P<username>\w+)/products/$', ManageProductView.as_view(), name='merchant_manage_products'),
    url(r'^(?P<username>\w+)/offerings/$', offering_list_view, name='offering_list'),
    url(r'^(?P<username>\w+)/offerings/approved/$', offering_action, name='offering_status'),
    url(r'^(?P<username>\w+)/(?P<product_slug>\w+)/$', edit_merchant_product, name='merchant_manage_indv_products'),
]

products/urls.py
from django.conf.urls import url

from products import views

urlpatterns = [
    url(r'^$', views.ProductListView.as_view(), name='product_listing'),
    url(r'^new/$', views.new_product, name='new_product'),
    url(r'^edit-product/(?P<slug>[\w\-]+)/$', views.edit_product, name='edit-product'),
    url(r'^(?P<slug>[\w\-]+)/$', views.product_detail, name='product_detail'),
    url(r'^(?P<slug>[\w\-]+)/offering/$', views.offering_view, name='offering_create'),
    url(r'^(?P<slug>[\w\-]+)/offering/(?P<id_params>\d+)/$', views.offering_view, name='offering_create'),
    url(r'^(?P<slug>[\w\-]+)/new-offer/$', views.counter_offer_view, name='counter_offer'),
    url(r'^(?P<slug>[\w\-]+)/new-offer/(?P<id_params>\d+)/$', views.counter_offer_view, name='counter_offer'),
    url(r'^offers/(?P<slug>[\w\-]+)/$', views.offerings_by_user, name='user_offers'),
]

merchant/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db import models
from accounts.models import UserProfile
from products.models import Product


class Merchant(models.Model):

    userprofile = models.OneToOneField(User)
    user_products = models.OneToOneField(Product, blank=True,)
    bank_acc_num = models.CharField(blank=True, default='', max_length=10)
    approved = models.BooleanField(default=False)

    def __unicode__(self):
        return u'Merchant with username %s' % (self.userprofile.username)

products/models.py
from cloudinary.models import CloudinaryField
from hvad.models import TranslatableModel, TranslatedFields
from multiselectfield import MultiSelectField
from phonenumber_field.modelfields import PhoneNumberField
from smart_selects.db_fields import ChainedForeignKey

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django_libs.models_mixins import TranslationModelMixin
from datetime import datetime


def valid_pct(val):
    if val.endswith("%"):
       return float(val[:-1])/100
    else:
       try:
          return float(val)
       except ValueError:          
          raise ValidationError(
              _('%(value)s is not a valid pct'),
                params={'value': value},
           )

class Product(models.Model):
    user = models.ForeignKey(User)
    price = models.IntegerField()
    quantity = models.IntegerField(blank=True, default=1)
    owner = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(blank=True, default='')
    slug = models.SlugField(blank=True, null=False, unique=True)
    name = models.CharField(max_length=100, null=False, blank=False)
    address = models.CharField(max_length=100, blank=False, default='')
    date_created = models.DateField(auto_now_add=True)
    date_last_modified = models.DateField(auto_now=True)
    commission = models.CharField(max_length=10, validators=[valid_pct])
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/product/{}/" .format(self.id)


class ProductPhoto(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    product = models.ForeignKey(Product, null=True, blank=True)
    image = CloudinaryField(
        resource_type='image',
        type='upload',
        blank=True,
        default="http://res.cloudinary.com/theeventdiary/image/upload/v1483614044/lg_m8sc17.jpg",
    )

    """ Informative name for mode """
    def __unicode__(self):
        try:
            public_id = self.image.public_id
        except AttributeError:
            public_id = ''
        return "Photo <%s:%s>" % (self.product, public_id) or u''


class Offering(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    customer_name = models.CharField(max_length=100, null=False, blank=False)
    customer_email = models.EmailField(max_length=70, blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    address = models.CharField(max_length=100, null=False, blank=False)
    is_approved = models.BooleanField(default=False)
    counter_price = models.IntegerField(blank=True, null=True)
    previous_counter_price = models.IntegerField(blank=True, null=True)
    counter_price_text = models.CharField(max_length=250, blank=True, null=True)
    is_accepted = models.BooleanField(default=False)
    approved_price = models.IntegerField(blank=True, null=True)
    date_created = models.DateTimeField(default=datetime.now, blank=True)
    date_last_modified = models.DateTimeField(default=datetime.now, blank=True)


class CounterOffering(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product) 
    customer_name = models.CharField(max_length=100, null=False, blank=False)
    customer_email = models.EmailField(max_length=70, blank=True, null=True)
    date_created = models.DateTimeField(default=datetime.now, blank=True)
    date_last_modified = models.DateTimeField(default=datetime.now, blank=True)


class OfferingStatus(TranslationModelMixin, TranslatableModel):
    """
    Master data containing all offering status.
    For translatable fields check ``OfferingStatusTranslation``.
    :slug: A unique slug identifier.
    translated:
    :name: The displayable name for the status.
    """
    slug = models.SlugField(
        verbose_name=_('Slug'),
    )

    translations = TranslatedFields(
        name=models.CharField(
            verbose_name=_('Name'),
            max_length=128,
        )
    )
        

merchant/forms.py
from django import forms
from .models import Merchant

class MerchantForm(forms.ModelForm):

    class Meta:
        model = Merchant
        fields = ['bank_acc_num']

    def save(self, commit=True):

        merchant_user = super(MerchantForm, self).save(commit=False)
        merchant_user.approved = False

        if commit:
            merchant_user.save()
        return merchant_user

products/forms.py
import datetime
from django import forms
from django.db import models
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.admin import widgets
from cloudinary.forms import CloudinaryJsFileField, CloudinaryUnsignedJsFileField

from .models import Offering, OfferingStatus, Product, ProductPhoto, CounterOffering


class OfferingForm(forms.ModelForm):

    def __init__(self, user, product, *arg, **kwargs):
        self.user = user
        self.product = product
        super(OfferingForm, self).__init__(*arg, **kwargs)
        self.fields['phone_number'].error_messages = {'invalid': 'Please make sure you use your country code (e.g. +2340000000000)', 'required': 'Enter a valid phone number'}

    class Meta:
        model = Offering
        fields = ['customer_name', 'customer_email', 'phone_number', 'address']


class CounterOfferForm(forms.ModelForm):

    def __init__(self, user, product, *arg, **kwargs):
        self.user = user
        self.product = product
        super(CounterOfferForm, self).__init__(*arg, **kwargs)

    class Meta:
        model = Offering
        fields = ['counter_price', 'counter_price_text']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", 'quantity', "address", "description"]


class ImageForm(forms.ModelForm):    
    class Meta:
        model = ProductPhoto
        fields = ['image']

merchant/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View, ListView
from django.shortcuts import render, render_to_response, HttpResponseRedirect
from django.contrib.auth.models import User
from django.forms import modelformset_factory
from django.core.mail import EmailMultiAlternatives
from django.template import RequestContext, Engine, loader

from products.baseviews import ProductListBaseView
from products.forms import ProductForm, ImageForm
from products.models import Product, ProductPhoto, Offering
from products.context_processor import Image_Effects

LOGIN_URL = '/login/'
EMAIL_SENDER = 'karamba.com.ng'

class ManageProductView(ProductListBaseView):
    """Manage a single product"""

    def get(self, request, username):
        """Renders a page showing a product that was created by a merchant
        """

        list_title = "My Products"
        list_description = "All products posted by you"
        template = "product.html"

        if request.user.is_authenticated:
            if request.user.userprofile.is_merchant:
                merchant_id = request.user.id
                products = Product.objects.filter(user_id=merchant_id)
                # get the rendered list of deals
                rendered_product_list = self.render_product_list(request, queryset=products, title=list_title, description=list_description, username=request.user)
                context = {
                    'rendered_product_list': rendered_product_list,
                    'Image_Effects' : Image_Effects,
                }
                return render(request, template, context)
            else:
                messages.add_message(
                    request, messages.INFO,
                    'Forbidden Page'
                )
                return redirect(reverse('product_listing'))
        else:
            messages.add_message(
                request, messages.ERROR,
                'You need to log in to view this page'
            )
            return redirect(reverse('login'))

@login_required(login_url=LOGIN_URL)
def offering_list_view(request, username):
    merchant_id = request.user.id
    products = Product.objects.filter(user_id=merchant_id)
    offering_list = list()

    for product in products:
        offerings = Offering.objects.filter(product_id=product.id).order_by('date_last_modified')
        for i, offering in enumerate(offerings):
            offering_dict = {
                'offering': offering
            }
            offering_list.append(offering_dict)
    return render(request, "manage_offerings.html", {'offering_list': offering_list})

def offering_action(request, username):
    merchant_id = request.user.id
    products = Product.objects.filter(user_id=merchant_id)
    offering_list = list()
    ids = list()

    for product in products:
        offerings = Offering.objects.filter(product_id=product.id)
        for i, offering in enumerate(offerings):
            offering_dict = {
                'offering': offering
            }
            offering_list.append(offering_dict)

    for o_list in offering_list:
        offering_id = o_list.get('offering').id
        ids.append(offering_id)

    for i in ids:
        action_button_clicked = request.GET.keys()
        for val in action_button_clicked:
            offering = Offering.objects.filter(id=i).get()
            args = dict()
            if val == 'accept':
                if offering.is_accepted == False:
                    offering.is_accepted = True
                    offering.approved_price = offering.counter_price
                    args["email"] = offering.customer_email
                    args["name"] = offering.customer_name
                    offering.save()
                    return render(request, 'manage_offering_success.html', args)
            if val == 'approve':
                if offering.is_approved == False:
                    offering.is_approved = True
                    args["email"] = offering.customer_email
                    args["name"] = offering.customer_name
                    offering.save()
                    # send email to customer of approval
                    product = Product.objects.filter(id=offering.product_id).get()

                    offering_approved_email_context = RequestContext(
                        request,
                        {
                            'product_name': product.name,
                            'product_description': product.description,
                            'username': offering.customer_name,
                            'offering': offering.phone_number,
                        },
                    )

                    receipient = str(offering.customer_email)

                    subject, from_email, to = 'Bargain.ng: Offer Approved', EMAIL_SENDER, receipient
                    html_content=loader.get_template('offering_approved.html').render(offering_approved_email_context)
                    text_content=loader.get_template('offering_approved.txt').render(offering_approved_email_context)

                    msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
                    msg.attach_alternative(html_content, "text/html")
                    response = msg.send()

                    if response == 1:
                        messages.add_message(request, messages.INFO, 'Purchase approved')

                    return render(request, 'manage_offering_success.html', args)

                else:
                    messages.add_message(
                        request, messages.ERROR,
                        'This request as already being approved by you.'
                    )
                return render(request, "manage_offerings.html", {'offering_list': offering_list})

@login_required(login_url=LOGIN_URL)
def edit_merchant_product(request, username, product_slug=None):
    """Updates information about a product that was created by a merchant.
    """

    product = Product.objects.get(slug=product_slug)
    ImageFormSet = modelformset_factory(ProductPhoto, form=ImageForm)

    if product.user.userprofile.is_merchant != request.user.userprofile.is_merchant:
        messages.add_message(
            request, messages.ERROR,
            'You are not allowed to manage this product'
        )
        return redirect(reverse('product_listing'))

    if request.method == 'POST':
        productform = ProductForm(request.POST, instance=product)
        formset = ImageFormSet(request.POST, request.FILES, queryset=ProductPhoto.objects.filter(product=product))

        if productform.is_valid() and formset.is_valid():
            productform.save(product)
            for form in formset:
                try:
                    image = form.cleaned_data['image']
                    photo = ProductPhoto(product=product, image=image)
                    photo.user_id = request.user.id
                    photo.save()
                except:
                    messages.error(request, 'Technical error')

            messages.add_message(
                request, messages.SUCCESS, 'The product was updated successfully.'
            )
        else:
            messages.add_message(
                request, messages.ERROR,
                'An error occurred while performing the operation.'
            )
        return redirect(reverse('merchant_manage_products', kwargs={'username': request.user}))
    else:
        form = ProductForm(instance=product)
        formset = ImageFormSet(queryset=ProductPhoto.objects.filter(product=product))
    return render(request, 'product_edit.html', {'form': form, 'formset': formset})

merchant/templates/manage_offering_success.html
{% extends "standard_page.html" %}
{% load static %}

{% block main %}
    {% if messages %}
        <div class="col-sm-12 no-left">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ message|safe }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="card">
        <div class="card-block">
            <h4 class="card-title">You have approved purchase made by {{name}} and an email has been sent to {{email}}</h4>
            <a href="{% url 'offering_list' username=request.user %}" class="btn btn-primary" id="{{ center_id }}">Back to offerings table<a/>
        </div>
    </div>
{% endblock main %}

merchant/templates/manage_offerings.html
{% extends "standard_page.html" %}
{% load static %}

{% block extended_css %}
    <link rel="stylesheet" href="{% static 'css/merchant/booking_table.css' %}" />
{% endblock extended_css %}

{% block main %}
    {% if messages %}
        <div class="col-sm-12 no-left">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ message|safe }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="container">           
        <table class="table table-hover">
            <thead class="table-head">
                <tr>
                    <th>Product</th>
                    <th>Product Price</th>
                    <th>Customer Name</th>
                    <th>Customer Email</th>
                    <th>Phone number</th>
                    <th>Counter Price</th>
                    <th>Previous Offer</th>
                    <th>Offer text</th>
                    <th>Approved</th>
                    <th>Approved Price</th>
                    <th>Action</th>
                </tr>
            </thead>
            {% for offering in offering_list %}
                <tbody>
                    <tr>
                        <td>{{offering.offering.product}}</td>
                        <td>{{offering.offering.product.price}}</td>
                        <td>{{offering.offering.customer_name}}</td>
                        <td>{{offering.offering.customer_email}}</td>
                        <td>{{offering.offering.phone_number}}</td>
                        <td>{{offering.offering.counter_price}}</td>
                        <td>{{offering.offering.previous_counter_price}}</td>
                        <td>{{offering.offering.counter_price_text}}</td>
                        <td>{{offering.offering.is_approved}}</td>
                        <td>{{offering.offering.approved_price}}</td>
                        <td>
                            <form action="{% url 'offering_status' username=request.user %}" method="get">
                                {% if offering.offering.counter_price and not offering.offering.approved_price %}
                                    <a type="submit" class="btn btn-primary" id="{{offering.offering.id}}" href="{% url 'counter_offer' slug=offering.offering.product.slug id_params=offering.offering.id %}">Counter Offer</a>
                                    <input type="submit" class="btn btn-primary" value="Accept" name="accept" id="{{offering.offering.id}}">
                                    <input type="submit" class="btn btn-danger" value="Decline" name="decline" id="{{offering.offering.id}}">
                                {% else %}
                                    <input type="submit" class="btn btn-primary" value="Approve" name="approve" id="{{offering.offering.id}}">
                                    <input type="submit" class="btn btn-danger" value="Decline" name="decline" id="{{offering.offering.id}}">
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    </div>
{% endblock %}

merchant/templates/offering_approved.html
<html>
<head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
    <body>
        <div style="overflow: auto;">

            <p style="display: none; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;">
                Determine How Much You want to Get a Product!
            </p>

            <div style="background-color: #dedede; min-height: 504px; line-height: 1.6; margin: auto; padding: 10%; padding-top: 4%; width: 70%; text-align: center; border-radius: 10px 10px 10px 10px;">
                    <p style="font-family: 'Montserrat', sans-serif; font-weight: 300; font-style: normal; color: #fff; font-size: 25px; text-decoration: none;">bargain.ng
                    </p>
                    <div style="background-color: #fff;font-family: Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif;font-size: 14px; font-weight: normal; display: block; margin: auto; max-width: 80%; padding: 10%;vertical-align: top; text-align: left; border-radius: 10px 10px 10px 10px;">

                        <h1 style="color: #909090; margin: 0;">Approved Transaction</h1>
                        <p>Hello {{username}},</p>
                        <div style="color: #444"
                            <p>Thank you for choosing bargain.ng. Your purchase has been approved and being processed. Below are the details of your orders;
                                <span>Product Name: {{product_name}}</span>
                                <br>
                                <span>Product Description: {{product_description}}</span>
                                <br>
                                <span>Name: {{username}}</span>
                                <br>
                                <span>Phone Number: {{offering}}</span>
                                <br>
                    </div>
                            </p>



                              <!--   <p style="margin: 0; margin-bottom: 15px; padding: 0; color: #444;">If nothing happens in the next 20 minutes, kindly reply this mail or call us on 08175395772.
                                </p> -->

                        <div style="border-collapse: separate; border-spacing: 0; width: auto; margin-bottom: 15px; text-align: left; vertical-align: top;">

                    <p style="color: #444">Thank you,</p>
                    <p style="color: #444">bargain.ng Team.</p>
                    </div>

                </div>
                <p align="center" style="font-size:13px; color: #A9A9A9;">Please disregard this email if you did not make a booking on bargain.ng.</p>
            </div>
        </div>
    </body>
</html>

merchant/templates/product.html
{% extends "standard_page.html" %}
{% load cloudinary %}
{% load static %}

{% block extended_css %}
    <link rel="stylesheet" href="{% static 'css/products/center_styling.css' %}">
{% endblock extended_css %}


{% block main %}
    {% if messages %}
        <div class="col-sm-12 no-left">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ message|safe }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row container-fluid" id="deals-section">
        {% for products in rendered_product_list.listing %}
            <div>{{products.centerphoto_set.all}}</div>
            <div class="col-md-4">
                <div class="card">
                    {% for image in products.productphoto_set.all|slice:"1" %}
                        {% cloudinary image.image Image_Effects.LISTING %}
                    {% endfor %}
                    <div class="card-block">
                        <h4 class="card-title">{{ products.name }}</h4>
                        <p class="card-text">{{ products.price }}</p>
                        <p class="card-text updated"><small class="text-muted">Last updated {{ products.date_last_modified }}</small></p>
                        <p class="read-on">
                            <a href="{% url 'product_detail' slug=products.slug %}">More details</a>
                        </p>
                        {% if request.user.userprofile.is_merchant %}
                            <a href="{% url 'merchant_manage_indv_products' username=request.user product_slug=products.slug %}" class="btn btn-primary edit">Manage Your Products</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock main %}